### ISSUE TITLE
Thumbnail going wrong

### ISSUE THREAD

**Issue by BakkerBE** [ThatGuySam/vumbnail#33]
Hi @ThatGuySam,

Something went wrong with my thumbnail creation on vumbnail.com 

The responsive JPG doesn't seem to load a new thumbnail selected in Vimeo, while the other formats (large, medium and small .jpg) are. Do you have any idea what's up? :)

video ID: 766837782

**Comment by ThatGuySam** [comment]
I can't seem to duplicate that issue. 

Is there anything else I can do to get what you're seeing? 

https://user-images.githubusercontent.com/2830379/201497283-6eaaf8d1-73f5-4ffa-809a-5f14639df29d.mov

**Comment by BakkerBE** [comment]
It seems it has sorted itself out over time (seeing your response), perhaps an update issue on Vimeo's side?..

**Comment by ThatGuySam** [comment]
@BakkerBE That's great! 

Yeah, sometimes Vimeo has outages.
