### ISSUE TITLE
Animated thumbnails question

### ISSUE THREAD

**Issue by miloandco** [ThatGuySam/vumbnail#4]
Hi,

Thanks for a good package. Do you have an update on the animated thumbnails? :-)

**Comment by ThatGuySam** [comment]
Hey, thanks for asking. 

Still working out how to render from the file. 

Do you have a specific implementation you're working on?

**Comment by ThatGuySam** [comment]
@miloandco I've created a new discussion for Animated Thumbnails: 
https://github.com/ThatGuySam/vumbnail/discussions/19
