### ISSUE TITLE
Support for non traditional vimeo URL

### ISSUE THREAD

**Issue by josephrexme** [ThatGuySam/vumbnail#9]
I tried using this URL https://vimeo.com/579958628/c8b4fb043c with vumbnail but it seem like it's not able to handle this kind of URL just yet. I wouldn't mind putting in a PR

**Comment by ThatGuySam** [comment]
I like this idea. 

We would need some tests to confirm certain features stay working as expected.

**Comment by josephrexme** [comment]
I would've loved to create a PR for this but I might not have the time to do so anymore (that's why I closed). If anyone comes here and is interested in doing it, I'd suggest replacing this line https://github.com/ThatGuySam/vimeo-thumbnail-server/blob/master/api/video.js#L22 with something that uses:
```
https://vimeo.com/api/oembed.json?url={FULL_FORMED_URL}
```

What I had in mind was to let people with such non-conventional URL to use vumbnail like:
```
vumbnail.com/579958628:c8b4fb043c
```

**Comment by vitexikora** [comment]
Please re-open!

**Comment by ThatGuySam** [comment]
Done! I’m working on some new features right now and will provide a canary link when they are ready

**Comment by ThatGuySam** [comment]
Right now I'm planning on using the following URL formats and I'd love to get your feedback on them:

`https://vumbnail.com/579958628:c8b4fb043c.jpg`
`https://vumbnail.com/579958628:c8b4fb043c_medium.jpg`
`https://vumbnail.com/579958628:c8b4fb043c_small.jpg`

**Comment by vitexikora** [comment]
Yes, this is great!

**Comment by ThatGuySam** [comment]
Private Thumbnails are now deployed to Canary: 
https://canary.vumbnail.com/579958628:c8b4fb043c.jpg

You can test it out with the following code: 
```html
<!-- Source Video: https://vimeo.com/579958628/c8b4fb043c -->
<img 
    srcset="
        https://canary.vumbnail.com/579958628:c8b4fb043c_large.jpg 640w, 
        https://canary.vumbnail.com/579958628:c8b4fb043c_medium.jpg 200w, 
        https://canary.vumbnail.com/579958628:c8b4fb043c_small.jpg 100w
    " 
    sizes="(max-width: 640px) 100vw, 640px" 
    src="https://canary.vumbnail.com/579958628:c8b4fb043c.jpg" 
    alt="Vimeo Thumbnail"
/>
```

Canary is for testing new features that have not been battle-tested yet so, if you use this in production, make sure to remove the `canary.` after Private Thumbnails are fully deployed to `https://vumbnail.com` or your thumbnail will almost certainly break at some point. 

I'll be slowly rolling this new version out a segment at a time just in case there are any random bugs that up. 

I'll announce it on this issue and the [email list](https://docs.google.com/forms/d/e/1FAIpQLSeFU6f19pAEJMI8yJYOzGIV8y8Sg5NvSnaM6tXz83VtvZeU7Q/viewform) once Private Thumbnails are fully deployed to production.

**Comment by ThatGuySam** [comment]
Support for Unlisted Vimeo Videos is now live! 

You can read the documentation here: 
https://vumbnail.com/examples/unlisted-vimeo-thumbnails
